### ISSUE TITLE
Remake `number.is-float` and `number.is-int` without comparing to `0.0` or `0`

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo-math#104]
We decided that we won't transform `0.0` to `-0.0` in `eo-runtime` to get `FALSE` as the result of `0.0.eq 0`.

So we need to remake `number.is-float` and `number.is-int` without comparing to `0.0` and `0` because they both has 8 zero bytes and we don't know what zero (float or int) we are trying to compare to.

We figured out that it can be done with comparing to negation of the given number. `0.0.neg` => -0.0, `0.neg` => 0.

@Graur please assign me

**Comment by Graur** [comment]
@maxonfjvipon Great, thanks! The budget is 30 min

**Comment by maxonfjvipon** [comment]
@Graur since transformation 0.0 to -0.0 is solved, I close the issue

**Comment by Graur** [comment]
@maxonfjvipon Sure, thanks!
