### ISSUE TITLE
Remove `nan` and `infinites` from here

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo-math#105]
After [this ticket](https://github.com/objectionary/eo/issues/1253) is done `nan`, `positive-infinity` and `negative-infinity` will be placed in `eo-runtime`. So we need to remove them from `eo-math` and make sure all objects that use them works correctly with moved ones.

@Graur if it's relevant, please assign me

**Comment by Graur** [comment]
@maxonfjvipon Sure, the budget is 30 min

**Comment by 0pdd** [comment]
@maxonfjvipon 4 puzzles [#116](https://github.com/objectionary/eo-math/issues/116), [#117](https://github.com/objectionary/eo-math/issues/117), [#118](https://github.com/objectionary/eo-math/issues/118), [#119](https://github.com/objectionary/eo-math/issues/119) are still not solved.

**Comment by 0pdd** [comment]
@maxonfjvipon 5 puzzles [#116](https://github.com/objectionary/eo-math/issues/116), [#117](https://github.com/objectionary/eo-math/issues/117), [#118](https://github.com/objectionary/eo-math/issues/118), [#119](https://github.com/objectionary/eo-math/issues/119), [#124](https://github.com/objectionary/eo-math/issues/124) are still not solved.
