### ISSUE TITLE
Release `eo-math`

### ISSUE THREAD

**Issue by mximp** [objectionary/eo-math#122]
Latest corrections of the syntax

**Comment by mximp** [comment]
@yegor256 please release the library

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.1`

**Comment by mximp** [comment]
```
[1;31mERRORm] java.io.IOException: Failed while trying to save to /home/r/repo/target/eo/04-pull/org/eolang/array.eo
```
@yegor256 seems to be sporadical issue. Can we try once again.

**Comment by yegor256** [comment]
@mximp I don't think so, but let's try

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.1`

**Comment by mximp** [comment]
@yegor256 Got it - it must be related to `array.eo` to `tuple.eo`.

**Comment by Graur** [comment]
@yegor256 can you please try to release it one more time?

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.1`

**Comment by Graur** [comment]
@yegor256 Can you help to release `eo-math`?

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.0`

**Comment by maxonfjvipon** [comment]
@yegor256 please release with tag `0.4.1`

**Comment by maxonfjvipon** [comment]
@yegor256 please release with tag `0.4.1`
