### ISSUE TITLE
to move objects from `eo-runtime` of EO

### ISSUE THREAD

**Issue by Graur** [objectionary/eo-math#13]
It would be great if we could move objects from `org.eolang.math` package of `eo-runtime` (in EO) to this `eo-math` project.
Since we get rid of them from `float.eo` and `int.eo` according to [this](https://github.com/objectionary/on-the-origin-of-objects/blob/master/paper.tex#L386). Here they are:
- angle.eo
- number.eo
- random.eo
and some tests for them

@maxonfjvipon You can leave them as is or redo them. It's up to you. But keep the tests untouched please.
I can provide some help with this issue, if you want.

**Comment by maxonfjvipon** [comment]
@Graur Sure, I'll do it. I'll let you know if there're any problems

**Comment by maxonfjvipon** [comment]
@rultor release, tag is `0.1.0`

**Comment by maxonfjvipon** [comment]
@Graur I think that's it. What are we gonna do next? Remove these math objects from EO repo?

**Comment by Graur** [comment]
@maxonfjvipon I agree, great job! Thanks!
Then we need to place  your objects to `objectionary/home` project (or just change `+rt` meta there) and yes, remove them from `eo-runtime`

**Comment by maxonfjvipon** [comment]
@rultor release, tag is `0.1.2`

**Comment by maxonfjvipon** [comment]
@Graur it seems we're done here

**Comment by Graur** [comment]
@maxonfjvipon Perfectly, thanks!
