### ISSUE TITLE
Refactor objects in order to update `eo-maven-plugin` to `0.32.0`

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo-math#136]
[This PR](https://github.com/objectionary/eo-math/pull/130) fails because of `sparce-decoration` xsl which was introduced in `0.29.6`
Need to refactor objects and assure build successes

**Comment by levBagryansky** [comment]
@yegor256 can we release it in order to update home? to `0.5.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.0`
