### ISSUE TITLE
'number.power' can be implemented in EO instead of Jav

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-math#21]
Let's get rid of the atom and implement `number.power` in EO

**Comment by Graur** [comment]
@maxonfjvipon please, take this task. The budget is 30 minutes.

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#50](https://github.com/objectionary/eo-math/issues/50), [#51](https://github.com/objectionary/eo-math/issues/51) are still not solved.
