### ISSUE TITLE
`eo-math` release 

### ISSUE THREAD

**Issue by Graur** [objectionary/eo-math#26]
We need to:

- [ ] create corresponding release of `eo-math`
- [ ] add all `.eo` files from `eo-math` to `objectionary/home` project (by `.sh` script)

after #25

**Comment by Graur** [comment]
@maxonfjvipon please, take this task, the budget is 30 minutes

**Comment by yegor256** [comment]
@Graur I believe it's done

**Comment by Graur** [comment]
@yegor256 Agree
