### ISSUE TITLE
`(number 0).is-int` returns FALSE

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo-math#31]
`(number 0).is-int` must return TRUE

```
[] > is-int
  if. > @
    eq.
      ^
      0
    FALSE
    eq.
      div.
        ^
        ^
      1
```

**Comment by Graur** [comment]
@maxonfjvipon Indeed, it's a bug. Can you fix this? The budget is 30 minutes.

**Comment by maxonfjvipon** [comment]
@Graur I think it's done. Could you please make a release?

**Comment by Graur** [comment]
@maxonfjvipon I think I don't have enough permission to do it.
@yegor256 please help us to release `eo-math` up to `0.2.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.1`

**Comment by Graur** [comment]
@maxonfjvipon I believe it is done

**Comment by maxonfjvipon** [comment]
@Graur almost, just need to fix 2 tests that decorates `nop`. After [this](https://github.com/objectionary/eo/pull/957#pullrequestreview-1070898836)
