### ISSUE TITLE
implement random.pseudo in EO using QQ.sys.call or QQ.sys.win32

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-math#35]
Now, `random.pseudo` is using Java in order to get `currentTimeMillis()`. It's possible to get rid of Java, after we enable `gettimeofday` in eo-sys: https://github.com/objectionary/eo-sys/issues/5

**Comment by yegor256** [comment]
@mximp please, help or delegate

**Comment by mximp** [comment]
@potatmen please have a look

**Comment by potatmen** [comment]
@mximp as I see `eo.sys` module on the stage of PR. I am interested in implementing pseudo.random using this module!
Btw, I proved that random.pseudo has a uniform distribution with the old implementation, I believe I will need to do it once again after implementation it in EO right?

**Comment by mximp** [comment]
@potatmen The task is exactly about implementation of `Pseudo.random` using `eo.sys`.

> I believe I will need to do it once again after implementation it in EO right

Yes, would be good to validate.

**Comment by potatmen** [comment]
@mximp Ok, but still I'm waiting for the merge of your PR to start using this module.

**Comment by potatmen** [comment]
@mximp I have a question about how to use `gettimeofday` in EO. If I try to use it like this `QQ.sys.system.gettimeofday` I get an error `The attribute Δ of org.eolang.PhLocated has org.eolang.PhPackage instead of org.eolang.Data`. If like this `QQ.sys.call "gettimeofday"` then I get this error `EOorg.EOeolang.EOstringν17="Can't #copy() package object 'org.eolang.sys.call'"SF` 
[Code](https://pastebin.com/vW5LqTjp)

**Comment by mximp** [comment]
@potatmen The function is expected to be called like the following:
```
+alias org.eolang.sys.call

[] > get-time-of-day-test
  if. > @
    QQ.sys.uname.is-windows
    nop
    assert-that
      QQ.sys.call
        "gettimeofday"
      $.greater-than 0
```

**Comment by potatmen** [comment]
@mximp Trying to use it like you said proposed [code](https://pastebin.com/LSgxuVLL) and get `The alias "org.eolang.sys.call" is not used (unused-aliases:26)`

**Comment by mximp** [comment]
@potatmen It's strange.. Can you try to use just `call`?

**Comment by mximp** [comment]
Also can you try to examine `target/eo` folder for interim stages. In which `.xmir` the error appears?

**Comment by potatmen** [comment]
@mximp Tried to use just call, got this `Failed while trying to save to ./target/04-pull/org/eolang/call.eo: https://raw.githubusercontent.com/objectionary/home/85efb6667117cb1f2f003016da99800dec26c5b7/objects/org/eolang/call.eo`

**Comment by potatmen** [comment]
@mximp The directory you recommended to check has only `.csv` files and no `.xmir` files

**Comment by potatmen** [comment]
@mximp Btw, according to this [comment](https://github.com/objectionary/eo-sys/issues/9#issuecomment-1232782325) we can't use `sys.call` because it wasn't added to the Objectionary

**Comment by mximp** [comment]
> @mximp The directory you recommended to check has only `.csv` files and no `.xmir` files

@potatmen normally `target/eo` should have the following structure:
```
 \01-parse\
 \02-steps\
 \03-optimize\
 \04-pull\
 \05-pre\
 \06-resolve\
 \06-transpile\
 foreign.csv
 placed.csv
```



> @mximp I believe the current version of random written in Java is [here](https://github.com/objectionary/eo-math/blob/68dcb40303dbc63dfada9d29bc3ace2190e9d7da/src/main/java/EOorg/EOeolang/EOmath/EOrandom%24EOpseudo.java). If yes, may I just rewrite this version in EO and show to you?

That's is the point of the task - to re-write it in EO. Let's review it as par of PR.

**Comment by potatmen** [comment]
@mximp https://github.com/objectionary/eo-sys/compare/master...potatmen:eo-sys:master in this file I added random number generator, please check it out. I placed it to the `eo-sys` repo because it's successfully running inside this repo

**Comment by potatmen** [comment]
@mximp one thing I have noticed about `target/eo` is that there are no `sys` subfolder, I mean that there are subfolders of `math` `collections` and so `sys`. 
<img width="367" alt="Screenshot 2022-09-11 at 11 25 46 PM" src="https://user-images.githubusercontent.com/90863441/189535841-bcaab77c-0b8c-470b-a79c-ddc232013b6f.png">
Also, please take a look at this issue https://github.com/objectionary/eo-sys/issues/9, it's said that `sys.call` is not added to `objectionary`

**Comment by mximp** [comment]
> @mximp [objectionary/eo-sys@master...potatmen:eo-sys:master](https://github.com/objectionary/eo-sys/compare/master...potatmen:eo-sys:master) in this file I added random number generator, please check it out. I placed it to the `eo-sys` repo because it's successfully running inside this repo

@potatmen As far as I can tell this will look totally different when implemented in correct repo (`eo-math`). Let's wait for `eo-sys` is released properly and then solve this task.

**Comment by levBagryansky** [comment]
@Graur I guess I am able to solve the task

**Comment by mximp** [comment]
@Graur @levBagryansky It is relevant. Assigned.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#98](https://github.com/objectionary/eo-math/issues/98) is still not solved.
