### ISSUE TITLE
max and min in a "series"

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-math#36]
Would be nice to introduce a new object `series`, which would decorate an array. Then, we can have `max` and `min`:

```
max.
  QQ.math.series
    *
      5
      13
      -9
```

Later, we can implement `series.sum`, `series.average`, `series.expectancy`, etc.

**Comment by yegor256** [comment]
@maxonfjvipon @Graur what do you think?

**Comment by Graur** [comment]
@yegor256 Maybe `number` object would be a better candidate for these operations?

**Comment by Graur** [comment]
@maxonfjvipon Buget: 30 min

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#54](https://github.com/objectionary/eo-math/issues/54) is still not solved.
