### ISSUE TITLE
upgrade to EO 0.28.0

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-math#42]
After the changes introduced in EO 0.28.0, one of the tests fail here:

```
EOorg.EOeolang.EOmath.EOmod_into_while_and_seq_objectsTest.testWorks()  Time elapsed: 0.024 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError:
Expected: <5> equal to value
     but: was <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:117)
	at EOorg.EOeolang.EOmath.EOmod_into_while_and_seq_objectsTest.testWorks(EOmod_into_while_and_seq_objectsTest.java:170)

```

Please, upgrade and release new version of eo-math.

**Comment by yegor256** [comment]
@Graur please, help

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#44](https://github.com/objectionary/eo-math/issues/44) is still not solved.

**Comment by Graur** [comment]
@rultor release, tag is `0.2.2`

**Comment by Graur** [comment]
@yegor256 Can you help to release `0.2.2` version of `eo-math`, please? I have not enough permissions

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.2`

**Comment by Graur** [comment]
@yegor256 please close the ticket if you don’t have any further questions.

**Comment by yegor256** [comment]
@Graur thanks!

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#44](https://github.com/objectionary/eo-math/issues/44) is solved here.
