### ISSUE TITLE
number-tests.eo:317-320: We need to remove this nop...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo-math#44]
The puzzle `42-658d578c` from #42 has to be resolved: 

https://github.com/objectionary/eo-math/blob/74d91636c5fd5b72c970f5728844c92537cae7c0/src/test/eo/org/eolang/math/number-tests.eo#L317-L320

The puzzle was created by @Graur on 01-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@maxonfjvipon please pay attention to this new issue.

**Comment by maxonfjvipon** [comment]
@Graur I think it can be closed

**Comment by Graur** [comment]
@maxonfjvipon `0pdd` bot close this issue automatically, after current `@todo` will be removed

**Comment by 0pdd** [comment]
The puzzle `42-658d578c` has disappeared from the source code, that's why I closed this issue. //cc @maxonfjvipon
