### ISSUE TITLE
`number.log` and  `number.ln` objects needed

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo-math#53]
For [this](https://github.com/objectionary/eo-math/issues/50) ticket we need two new objects `number.log` and `number.ln`. 
 I think `log` should be implemented in Java for now, `ln` will decorate `log`.
@Graur, what do you think?

**Comment by Graur** [comment]
@maxonfjvipon I agree, go ahead! And don't forget to use PDD for `log` implementation by EO.
The budget is: 30 min

**Comment by Graur** [comment]
@levBagryansky please, help us here

**Comment by levBagryansky** [comment]
@Graur sure

**Comment by 0pdd** [comment]
@maxonfjvipon 2 puzzles [#69](https://github.com/objectionary/eo-math/issues/69), [#70](https://github.com/objectionary/eo-math/issues/70) are still not solved.
