### ISSUE TITLE
test with number.log fails

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo-math#71]
@Graur @maxonfjvipon please check
The tests with number.log fails with `stackoverfow`. Maybe we need to investigate this question.
[fail case](https://github.com/objectionary/eo-math/actions/runs/3410936675/jobs/5674513077).
More cases are in #65

**Comment by levBagryansky** [comment]
@Graur @maxonfjvipon My theory is it fails because of too many tests since [here](https://github.com/objectionary/eo-math/actions/runs/3410936675/jobs/5674513077) failed test with `nop > @`

**Comment by Graur** [comment]
@levBagryansky This PR #76 should help, please try to build it again

**Comment by levBagryansky** [comment]
@Graur Thanks!
