### ISSUE TITLE
number.eo:303-305: min. Implement exp using this taylor...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo-math#83]
The puzzle `56-a1660657` from #56 has to be resolved: 

https://github.com/objectionary/eo-math/blob/a61f115a10a787c2ff52a411e483aaf678e3a7e5/src/main/eo/org/eolang/math/number.eo#L303-L305

The puzzle was created by levBagryansky on 10-Nov-22. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@maxonfjvipon please pay attention to this new issue.

**Comment by levBagryansky** [comment]
@Graur please assign me

**Comment by Graur** [comment]
@levBagryansky Sure, go ahead

**Comment by includealex** [comment]
@Graur @levBagryansky do we really need `taylor` object for counting exponent?
We know that in taylor series $e^x$ looks like:
$$e^x = 1 + \frac{x}{1!} + \frac{x^2}{2!} + \frac{x^3}{3!} + ...$$
But we can rewrite it as
$$e^x = 1 + \frac{x}{1} \cdot(1 + \frac{x}{2} \cdot(1 + \frac{x}{3} \cdot (...)))$$
For example, C++ implementation looks like this:
```c++
float exp(size_t n, float x) {
  float sum = 1.0f;
  for (size_t i = n - 1; i > 0; --i) {
    sum = 1 + x * sum / i;
  }
  return sum;
}
```

**Comment by includealex** [comment]
In the given example `n` means that we are using first n terms of Taylor Series.

**Comment by levBagryansky** [comment]
@includealex Indeed. Seems this way is better because allows to calculate more terms in series

**Comment by levBagryansky** [comment]
@includealex We also can use definition of `exp`:
$$\exp(x) = \lim\limits_{n \to \infty} (1 + \frac{x}{n})^n$$

**Comment by includealex** [comment]
@levBagryansky it is a good idea, but I think that it would be not as accurate, as we want. If we take `n=1e9`, the 6 symbol after the dot will be incorrect.

**Comment by levBagryansky** [comment]
@includealex I am now implementing exp(x) according to https://www.javamex.com/tutorials/math/exp.shtml
Briefly, It firstly separate x by two parts: x0 and x1. x0 is less than ln(2) so it can be computed by definition. x1 is number of multiples of ln(2) so exp(x1) can be calculated via `(number 2).power (x/ln(2))`(pseudo-code). ln(2) is a constant
