### ISSUE TITLE
number.sqrt object

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo-math#89]
There is a separate function of sqrt in defferent languages. For instance `Math.sqrt` in java. I think it would be useful to have this object too. We can use [Heron's iterative formula](https://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Babylonian_method) instead of calculating method in `number.power` because the formula has a good convergence rate: 
$$\\sqrt{S} = \lim\limits_{k \to \infty} x_{k}$$
$$x_{k+1} = \frac{1}{2} * (x_{k} + \frac{S}{x_{k}}) $$
@Graur @EugeneDar WDYT?

**Comment by EugeneDar** [comment]
@levBagryansky I don't mind

**Comment by Graur** [comment]
@maxonfjvipon WDYT?

**Comment by maxonfjvipon** [comment]
@levBagryansky @Graur I like the idea about the Heron's formula. I have just a question: will we have an object to calculate a root of a n'th degree (n can be float as well)? 
1. If yes then I think maybe we should introduce some universal object to calculate the root and make a special algorithm (Neron's) for `n = 2` (or even for `n` = 2, 4, 8, 16, 32, ... 2^x)?
2. If no then `sqrt` fits good here

**Comment by levBagryansky** [comment]
@maxonfjvipon may be it is better to use the method in `number.power` if `x` is less than 1.0? Otherwise we would have 2 almost same objects: `power` and `root`. So I guess it is better to have just `sqrt`

**Comment by maxonfjvipon** [comment]
@levBagryansky ok, I agree

**Comment by 0pdd** [comment]
@levBagryansky the puzzle [#92](https://github.com/objectionary/eo-math/issues/92) is still not solved.
