### ISSUE TITLE
number.is-close

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo-math#90]
@Graur @maxonfjvipon 
I think it would be convenient to use `number.is-close` in order to comparison floats. I would simplify coding tests
WDYT about introducing this object?
`[accuracy other] > close`

**Comment by levBagryansky** [comment]
@Graur maybe we can make it a matcher

**Comment by Graur** [comment]
@levBagryansky Do you mean something like that: https://github.com/objectionary/eo-hamcrest/blob/master/src/main/eo/org/eolang/hamcrest/matchers/close-to-matcher.eo ?

**Comment by levBagryansky** [comment]
@Graur yes)
