### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by c71n93** [objectionary/eo-math#99]
I needed `sqrt` attribute of `number`, but it wasn't in release. There were implemented list of things, maybe we can make a release?

**Comment by c71n93** [comment]
@yegor256 @Graur what do you think about it?

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.0`

**Comment by yegor256** [comment]
@Graur what's up with this? let's try to release a fresh version with the latest EO 0.29.0

**Comment by Graur** [comment]
@yegor256 Sure, I can do it. But I suggest to merge this pull request first: https://github.com/objectionary/home/pull/100

**Comment by yegor256** [comment]
@Graur it's released

**Comment by Graur** [comment]
@yegor256 I can't do it because of redundant parenthesis in `objectionary/home`: https://github.com/objectionary/home/issues/101
So, I want to fix it at `home` first. And then I can create a pull request here to release `eo-math`

**Comment by 0pdd** [comment]
@c71n93 2 puzzles [#110](https://github.com/objectionary/eo-math/issues/110), [#111](https://github.com/objectionary/eo-math/issues/111) are still not solved.

**Comment by Graur** [comment]
@yegor256 Can we try to release it one more time?

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.0`

**Comment by Graur** [comment]
@yegor256 Looks like there is no `eo-runtime` dependency in `pom.xml`. I will fix it in separated pull request

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.0`
